# 张量运算

## 1 张量的逐元素运算（点对点）

#### 进行平方运算

In [7]:
import numpy as np

x = np.array([
    [5,-78,2,34,0],
    [6,79,-3,35,1],
    [7,80,4,36,-2],
])

In [14]:
pow(x,2)

array([[  25, 6084,    4, 1156,    0],
       [  36, 6241,    9, 1225,    1],
       [  49, 6400,   16, 1296,    4]], dtype=int32)

#### 进行加法运算

In [16]:
x + 1

array([[  6, -77,   3,  35,   1],
       [  7,  80,  -2,  36,   2],
       [  8,  81,   5,  37,  -1]])

#### 实现Dense层所用到的relu函数，实现对数据进行非负化处理，即只保留大于或等于0的数

In [18]:
def naive_relu(x):
    
    
    y = x.copy()
    
    for i in range(y.shape[0]):#遍历行
        for j in range(y.shape[1]): #遍历列
            y[i,j] = max(y[i,j], 0) #relu函数功能
                
    return y

In [11]:
print('relu激活前的张量：\n'+ str(x) + "\n")
print('relu激活后的张量：\n'+ str(naive_relu(x)))

relu激活前的张量：
[[  5 -78   2  34   0]
 [  6  79  -3  35   1]
 [  7  80   4  36  -2]]

relu激活后的张量：
[[ 5  0  2 34  0]
 [ 6 79  0 35  1]
 [ 7 80  4 36  0]]


## 2 张量的广播，即不同维度张量的运算

### 1个2D张量（矩阵）与1个1D张量(向量)相加

In [23]:
#2D张量
x1 = np.array([
    [5,-78,2,34,0],
    [6,79,-3,35,1],
    [7,80,4,36,-2],
])

#1D张量
x2 = np.array([1,2,3,4,5])

x1 + x2

array([[  6, -76,   5,  38,   5],
       [  7,  81,   0,  39,   6],
       [  8,  82,   7,  40,   3]])

### 一个张量形状为(a,b,c,d)，另一个张量形状为(c,d),进行运算

In [15]:
x = np.random.random((64,3,32,10))
y = np.random.random((32,10))

In [16]:
x * y

array([[[[2.40216591e-01, 8.23586564e-01, 7.52236203e-01, ...,
          2.17271125e-02, 6.50271253e-01, 3.64729643e-01],
         [2.57987343e-03, 7.09487666e-01, 1.26574168e-02, ...,
          1.71815495e-02, 7.48448389e-01, 8.63219246e-01],
         [7.45178879e-01, 2.24110828e-02, 3.80813135e-01, ...,
          6.30151592e-02, 2.89700475e-01, 5.17442538e-02],
         ...,
         [2.37923594e-01, 5.35130184e-02, 2.72176516e-01, ...,
          4.77861756e-01, 7.92471730e-02, 1.22119475e-01],
         [1.48175932e-01, 1.17928464e-02, 2.90026173e-01, ...,
          2.94264303e-01, 7.54383857e-01, 1.29841572e-01],
         [1.33234875e-01, 2.61393535e-01, 1.52836592e-01, ...,
          1.27925221e-01, 1.73472812e-02, 2.35439450e-04]],

        [[1.06889107e-01, 8.01906058e-01, 1.12011997e-01, ...,
          1.30925282e-01, 6.95890712e-01, 4.44236915e-01],
         [1.02946501e-02, 3.28887076e-01, 1.93660652e-02, ...,
          1.10116481e-01, 5.50112305e-02, 8.70202654e-01],
        

## 3 张量的乘积与点积

### 3.1 乘积，用*实现乘积，即逐元素点对点相乘，得到的结果仍为多维张量
#### 两个张量的shape不一致也可以进行乘积运算

In [4]:
#初始化一个2 x 2矩阵
x = np.array([
    [1,1],
    [1,1]    
])
print(x)

[[1 1]
 [1 1]]


In [6]:
x * np.array([2,2])

array([[2, 2],
       [2, 2]])

### 3.2 点积（内积/数量积），用np.dot实现，元素之间先乘积后求和，得到的结果为标量
### 乘数的矩阵列与被乘数的矩阵行数要保持一致，且元素总数保持一致

In [30]:
np.dot(x,x)

array([[2, 2],
       [2, 2]])

## 4 张量的变形，用函数reshape实现，即属性shape的变换，但维持总元素数不变

In [32]:
#初始化一个 3 x 4 x 5的3D张量 
x = np.random.random((3,4,5))
x

array([[[0.62158498, 0.58909226, 0.08467623, 0.85441062, 0.51544233],
        [0.61728797, 0.33531183, 0.72208789, 0.7809586 , 0.42848016],
        [0.28999944, 0.42066883, 0.61672473, 0.16036017, 0.53571446],
        [0.63386087, 0.93006316, 0.42755319, 0.65111737, 0.84688077]],

       [[0.3965008 , 0.63895401, 0.04119715, 0.86718621, 0.91047324],
        [0.47459079, 0.3784236 , 0.15411898, 0.33853635, 0.18633624],
        [0.60547249, 0.53655964, 0.24719725, 0.15154832, 0.87266818],
        [0.45927646, 0.78939005, 0.52258529, 0.51555053, 0.16642919]],

       [[0.20667907, 0.63525131, 0.45128057, 0.97215266, 0.34398636],
        [0.76712608, 0.25589948, 0.83643801, 0.11057426, 0.39216495],
        [0.55586567, 0.46449081, 0.55817556, 0.48978286, 0.54068563],
        [0.80223577, 0.62748562, 0.83796396, 0.35876153, 0.70521695]]])

In [33]:
#将(3.4.5)3D张量 转换为 (3,20)矩阵
print(x.reshape(3,4 *5))

[[0.62158498 0.58909226 0.08467623 0.85441062 0.51544233 0.61728797
  0.33531183 0.72208789 0.7809586  0.42848016 0.28999944 0.42066883
  0.61672473 0.16036017 0.53571446 0.63386087 0.93006316 0.42755319
  0.65111737 0.84688077]
 [0.3965008  0.63895401 0.04119715 0.86718621 0.91047324 0.47459079
  0.3784236  0.15411898 0.33853635 0.18633624 0.60547249 0.53655964
  0.24719725 0.15154832 0.87266818 0.45927646 0.78939005 0.52258529
  0.51555053 0.16642919]
 [0.20667907 0.63525131 0.45128057 0.97215266 0.34398636 0.76712608
  0.25589948 0.83643801 0.11057426 0.39216495 0.55586567 0.46449081
  0.55817556 0.48978286 0.54068563 0.80223577 0.62748562 0.83796396
  0.35876153 0.70521695]]


In [37]:
#转置
print(np.transpose(x).shape)

(5, 4, 3)


In [32]:
x = np.random.random((3,4,5))
y = np.random.random((6,5,8))
np.dot(x,y)

array([[[[2.51476831, 1.97302446, 1.0677877 , 2.19921389, 1.97895249,
          2.59398383, 1.80196547, 1.41423748],
         [2.26319856, 2.5349884 , 1.79145312, 2.56659255, 1.92305367,
          1.70103602, 1.89539899, 1.93219459],
         [2.01359435, 2.61859017, 1.50876386, 0.68286847, 0.99469032,
          2.29111664, 1.28056923, 1.47587263],
         [2.91827475, 2.58783371, 1.99276086, 1.97112788, 3.01242558,
          1.57399071, 2.68017058, 1.44761285],
         [1.62088639, 3.10667824, 2.11484126, 1.782056  , 1.27238104,
          1.67469336, 1.25801322, 2.53343029],
         [2.84105183, 1.58607836, 2.129623  , 1.86806991, 2.19704561,
          2.54581266, 1.73713398, 1.87533335]],

        [[1.64685369, 1.2457779 , 0.52472836, 1.58928821, 1.29617152,
          1.65857399, 1.29834944, 0.91902186],
         [1.46949686, 1.2900764 , 1.12202993, 1.9144939 , 1.0355929 ,
          1.00767252, 1.23613924, 1.29806854],
         [1.28999042, 1.62170021, 1.10220022, 0.55070938, 0.60

In [35]:
x = np.array([[0,1],[2,3]])
y = np.array([[4,5],[6,7]])
np.dot(x,y)

array([[ 6,  7],
       [26, 31]])

## 5 用张量运算实现Dense层

### 实现 keras.layers.Dense(512,activation = 'relu',input = (28*28,))

In [8]:
import numpy as np
#初始化输入
inp= np.random.random((28 * 28,)) #28为图片长宽的像素数，32为batch_size，一个批次所包含的图片数
#inp= (np.random.randint(0,255,(28 * 28, 32))).astype('float')
print('输入张量的shape：'+ str(inp.shape))

#初始化权重参数
w1 = np.random.random((28*28,512))
print('权重参数张量的shape：'+ str(w1.shape))

#偏置向量
b1 = np.random.random((512,))
print('权重参数张量的shape：'+ str(b1.shape))

输入张量的shape：(784,)
权重参数张量的shape：(784, 512)
权重参数张量的shape：(512,)


In [9]:
#第1个dense层的激活函数 relu
def my_relu(x):
    
    
    y = x.copy()
    
    for i in range(y.shape[0]):#遍历行
        y[i] = max(y[i], 0) #relu函数功能
                
    return y

In [10]:
#点积-->加偏置-->relu运算
#注意，点积顺序与教材中不一致
outp1 = my_relu(np.dot(inp,w1) + b1)
print("第1个dense层的输出形状：" + str(outp1.shape))
print("第1个dense层的输出结果：" + str(outp1))

第1个dense层的输出形状：(512,)
第1个dense层的输出结果：[202.9450158  193.43503536 196.6803896  195.92121749 189.09367885
 191.38399945 191.05757111 195.94080171 188.91243415 193.33005828
 193.52761914 191.70205575 195.10065303 191.18006765 194.92499784
 193.05288968 191.4143047  191.4199833  187.88541966 202.27682625
 187.92044174 186.1603646  188.67956446 191.84536286 194.23494227
 188.95024685 199.5015616  187.07265623 195.54037243 186.22131917
 198.02436094 196.01680254 186.29318011 187.18710625 195.4731892
 202.30528788 190.35417045 191.90868912 199.83059091 190.25097457
 183.31292882 193.47189848 179.33734916 199.03908769 191.32849265
 184.50601358 196.27779371 201.54956976 198.7177755  189.35172414
 204.35091229 197.20056256 191.80393005 197.9408295  186.26262271
 192.26179922 199.19644055 186.98554452 197.54248527 196.99580669
 186.836323   195.66831108 199.26516761 195.84823531 194.68631213
 202.95272492 186.03499464 199.30399017 199.33837783 197.22524928
 188.41344456 187.85630045 191.36779348 

### 继续实现 keras.layers.Dense(10,activation = 'softmax')

In [11]:
#初始化权重参数
w2 = np.random.random((512,10))
print('权重参数张量的shape：'+ str(w2.shape))

#偏置向量
b2 = np.random.random((10,))
print('权重参数张量的shape：'+ str(b2.shape))

权重参数张量的shape：(512, 10)
权重参数张量的shape：(10,)


In [12]:
#先进行线性运算
outp2 = np.dot(outp1, w2) + b2
outp2.shape

(10,)

In [13]:
outp2

array([48112.06750664, 49903.83580993, 49466.72377985, 49130.76662218,
       48912.12951028, 49646.52280289, 50798.9076368 , 51992.42893782,
       49890.34768067, 50921.41789288])

In [14]:
#再使用softmax激活函数
import tensorflow as tf

sess = tf.InteractiveSession()
sess.run(tf.global_variables_initializer())

outp3 = tf.nn.softmax(outp2, axis=0)
print("第2个dense层输出形状：" + str(outp3))
print("第2个dense层输出结果：" + str(outp3.eval()))
sess.close()

第2个dense层输出形状：Tensor("Softmax:0", shape=(10,), dtype=float64)
第2个dense层输出结果：[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]


#### 从第二层输出概率中提取概率最大值标签类别

In [15]:
outp4 = tf.argmax(outp3,axis = 0) #选取概率最大的序号

sess = tf.InteractiveSession()
sess.run(tf.global_variables_initializer())

outp_final = tf.argmax(outp3,axis = 0)

print(outp_final)
print("模型预测数字为：%d"%outp_final.eval())
sess.close()

Tensor("ArgMax_1:0", shape=(), dtype=int64)
模型预测数字为：7
